COMMAND_CLASS_RGB = 0x33
COMMAND_CLASS_SWITCH = 0x25
COMMAND_CLASS_DIMMER = 0x26
COMMAND_CLASS_NOTIFICATION = 0x71

# Sensors
COMMAND_CLASS_SENSOR_BINARY = 0x30
COMMAND_CLASS_SENSOR_MULTILEVEL = 0x31
COMMAND_CLASS_METER = 0x32
COMMAND_CLASS_BATTERY = 0x80

DEVICE_CLASS_SENSOR = "sensor"
SENSORS = [COMMAND_CLASS_SENSOR_BINARY, COMMAND_CLASS_SENSOR_MULTILEVEL, COMMAND_CLASS_METER, COMMAND_CLASS_BATTERY,
           COMMAND_CLASS_NOTIFICATION]
